import { supabase } from './supabaseClient';

// Transaction API using Supabase
export const transactionAPI = {
  // GET all transactions for a month
  getAll: async (month) => {
    try {
      let query = supabase
        .from('transactions')
        .select('*')
        .order('date', { ascending: false });

      if (month) {
        query = query.eq('month', month);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data || [];
    } catch (error) {
      console.error('Error fetching transactions:', error);
      throw error;
    }
  },

  // GET single transaction
  getById: async (id) => {
    try {
      const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .eq('id', id)
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          throw new Error('Transaction not found');
        }
        throw error;
      }

      return data;
    } catch (error) {
      console.error('Error fetching transaction:', error);
      throw error;
    }
  },

  // POST create transaction
  create: async (transaction) => {
    try {
      const newTransaction = {
        id: transaction.id || `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        date: transaction.date,
        type: transaction.type,
        category: transaction.category,
        description: transaction.description,
        amount: parseFloat(transaction.amount),
        month: transaction.month,
        payment_method: transaction.payment_method || null,
        notes: transaction.notes || null,
        tags: transaction.tags || null,
        is_recurring: transaction.is_recurring || false
        // created_at and updated_at are auto-generated by the database
      };

      const { data, error } = await supabase
        .from('transactions')
        .insert([newTransaction])
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error creating transaction:', error);
      throw error;
    }
  },

  // PUT update transaction
  update: async (id, transaction) => {
    try {
      const updateData = {
        updated_at: new Date().toISOString()
      };

      if (transaction.date) updateData.date = transaction.date;
      if (transaction.type) updateData.type = transaction.type;
      if (transaction.category) updateData.category = transaction.category;
      if (transaction.description) updateData.description = transaction.description;
      if (transaction.amount !== undefined) updateData.amount = parseFloat(transaction.amount);
      if (transaction.month) updateData.month = transaction.month;
      if (transaction.payment_method !== undefined) updateData.payment_method = transaction.payment_method;
      if (transaction.notes !== undefined) updateData.notes = transaction.notes;
      if (transaction.tags !== undefined) updateData.tags = transaction.tags;
      if (transaction.is_recurring !== undefined) updateData.is_recurring = transaction.is_recurring;

      const { data, error } = await supabase
        .from('transactions')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          throw new Error('Transaction not found');
        }
        throw error;
      }

      return data;
    } catch (error) {
      console.error('Error updating transaction:', error);
      throw error;
    }
  },

  // DELETE transaction
  delete: async (id) => {
    try {
      const { data, error } = await supabase
        .from('transactions')
        .delete()
        .eq('id', id)
        .select();

      if (error) throw error;
      
      // Supabase returns an array, even for single deletes
      if (!data || data.length === 0) {
        throw new Error('Transaction not found');
      }

      return { message: 'Transaction deleted', transaction: data[0] };
    } catch (error) {
      console.error('Error deleting transaction:', error);
      throw error;
    }
  },
};

// Month API
export const monthAPI = {
  getAll: async () => {
    try {
      const { data, error } = await supabase
        .from('transactions')
        .select('month');

      if (error) throw error;

      const months = [...new Set(data.map(t => t.month))];
      months.sort((a, b) => b.localeCompare(a));
      return months;
    } catch (error) {
      console.error('Error fetching months:', error);
      throw error;
    }
  },
};

// Health check
export const healthCheck = async () => {
  try {
    const { error } = await supabase
      .from('transactions')
      .select('id')
      .limit(1);

    if (error) throw error;
    return { status: 'ok', timestamp: new Date().toISOString() };
  } catch {
    return null;
  }
};

// Search transactions
export const searchAPI = {
  search: async (query, month) => {
    try {
      let searchQuery = supabase
        .from('transactions')
        .select('*')
        .or(`description.ilike.%${query}%,category.ilike.%${query}%,notes.ilike.%${query}%`)
        .order('date', { ascending: false });

      if (month) {
        searchQuery = searchQuery.eq('month', month);
      }

      const { data, error } = await searchQuery;
      if (error) throw error;
      return data || [];
    } catch (error) {
      console.error('Error searching transactions:', error);
      throw error;
    }
  }
};

// Export functionality
export const exportAPI = {
  toCSV: (transactions) => {
    const headers = ['Date', 'Type', 'Category', 'Description', 'Amount', 'Payment Method', 'Notes', 'Tags'];
    const rows = transactions.map(t => [
      t.date,
      t.type,
      t.category,
      `"${(t.description || '').replace(/"/g, '""')}"`,
      t.amount,
      t.payment_method || '',
      `"${(t.notes || '').replace(/"/g, '""')}"`,
      t.tags || ''
    ]);
    
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `ledger_export_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  }
};
